seed: 42
data:
  filename: data/01_raw/data.xlsx
  type: excel
  X_column: text
  y_column: choose_one

preprocess:
  - spacy_lemmatization
  - spacy_lemmatization_rm_stopwords

split:
  val: 1000
  test: 1000

feature_engineering:
  bow:
    min_vectorizer_freq: 30
#  tfidf:
#    min_vectorizer_freq: 30
#  w2v:
#    epochs: 40
#    min_count: 3
#    window: 2
#    size: 300
#    sample: 0.00006
#    alpha: 0.03
#    min_alpha: 0.0007
#    negative: 20
#  fasttext:
#  w2v_pretrained:
#  bert:

feature_combination:
  bow+w2v:
    - bow
    - w2v

feature_selection:
  k_best_features: 180

modeling:
  - catboost
  - logreg